### ISSUE TITLE
Greek letters not displayed

### ISSUE THREAD

**Issue by panoskpv** [MDeLuise/plant-it#196]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

When a custom plant is added with name in greek language and saved, the plant created has a gibberish/symbol name.

**Comment by igorsantos07** [comment]
The web version has a several issue with text encoding - it can't even display the monetary symbols properly, and when I go to edit a plant, it refuses to save because the symbol is missing from the plant price.

This was from a fresh install, testing out the system:
![image](https://github.com/user-attachments/assets/84372a99-8e00-43d3-b8f6-23827abffb14)
