### ISSUE TITLE
Show future schedule of tasks

### ISSUE THREAD

**Issue by igorsantos07** [MDeLuise/plant-it#281]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

The calendar screen could have another option that shows upcoming tasks for tomorrow / next 7 and 30 days. This could help plan out in case you'll be out for a few days (and also checking if you set stuff up correctly haha)

**Comment by MDeLuise** [comment]
Hi @igorsantos07, thanks for the great idea!
This task has been completed and will be implemented in the next project release.
I'm closing the issue since done, but if you will have any further questions or updates regarding this task, feel free to leave a comment below.
<p align="center">
<img width="33%" src="https://github.com/user-attachments/assets/f477a879-8d85-4159-aee0-43e87f51dca7">
<img width="33%" src="https://github.com/user-attachments/assets/6b4bbafa-8a20-4115-9c53-5e19f899e45b">
</p>
