### ISSUE TITLE
Can't use Local environment

### ISSUE THREAD

**Issue by cesarblancg** [MDeLuise/plant-it#58]
### Question

Hi! I attempted to run it in my local environment to experiment with new features, but I’m unable to set the API key.

Steps:

Clone the repository.
Set the Trefle API key in the .env file.
Launch it with “./mvnw spring-boot:run -Dspring-boot.run.profiles=dev -DcopyFiles”.
Log in with user/user credentials.
How can I set the API key? It’s showing an error.

**Comment by MDeLuise** [comment]
Hi! Thanks for the feedback, I'm happy to hear that you want to try the app in a "developer mode".
You're right, I tried to run locally the backend as specified in the readme and it's not possible to change the default variable values using the `.env` file.
I didn't notice this before since I use IntelliJ to run the backend and I put the `TREFLE_KEY` as environment variable inside the profile I use for the app from the IDE.

### Problem
The problem is the following: the backend (spring) uses the provided `application[-profile].properties` files in order to read the variables. In those files there are the specified default values and global variable names to override these default values.

On the docker deployment, the `.env` file is passed as global variables so this works as expected.

### Temporary solution
As for now, you can:
* Export the needed variable globally (e.g. in bash `export TREFLE_KEY=...`). This has the advantages of not insert the key in any of the files, so you don't incur into committing sensitive information to the codebase.
* Or change the line in the `application-dev.properties` file from `trefle.key=${TRAFLE_KEY:}` to `trefle.key=...`. This has the advantages of making the changes "persistence" between different shell session, but remember to not commit the file otherwise your key will be exported.

### Long term solution
I have to understand how to make possible for spring to load external environment files. From a [first research](https://github.com/spring-projects/spring-boot/issues/24229) it seems that spring does not support external env file natively but there are some [plugins](https://github.com/paulschwarz/spring-dotenv) in order to achieve this.
